# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull code in github environment
      uses: actions/checkout@v4

    - name: Set up Go into the environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/awslearn .

    - name: Push docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/awslearn:latest

